version: "3"

services:
  frontend:
    image: nginx:1.19
    container_name: frontend_container
    links:
      - backend
    ports:
      - "4500:8080"
    volumes:
      - ./frontend/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/html:/var/www/html
    environment:
      TZ: "Asia/Tokyo"
    networks:
      - waninet

  backend:
    build: ./backend
    volumes:
      - ./backend/flaskapp:/app
    command: uwsgi --ini /app/uwsgi.ini
    container_name: backend_container
    links:
      - database
    ports:
      - "3031:3031"
    environment:
      TZ: "Asia/Tokyo"
    networks:
      - waninet
      
  database:
    image: mysql:5.7
    container_name: database_container
    ports:
      - "13306:13306"
    volumes:
      - ./database/conf.d:/etc/mysql/conf.d
      - ./database/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_TCP_PORT: 13306
      MYSQL_ROOT_PASSWORD: zK4R8Wfa
      MYSQL_DATABASE: wanitter
      MYSQL_USER: wani
      MYSQL_PASSWORD: pZ95C4kV
    networks:
      - waninet

networks:
  waninet:
    driver: bridge

